"""Application-wide constants."""

ELIGIBILITY_BAIXA_RENDA = "baixa renda"
ELIGIBILITY_RESPONSAVEL_IDOSO = "responsável idoso"
ELIGIBILITY_NECESSIDADE_MOBILIDADE = "necessita apoio de mobilidade"
ELIGIBILITY_FAMILIA_MONOPARENTAL = "família monoparental"

__all__ = [
    "ELIGIBILITY_BAIXA_RENDA",
    "ELIGIBILITY_RESPONSAVEL_IDOSO",
    "ELIGIBILITY_NECESSIDADE_MOBILIDADE",
    "ELIGIBILITY_FAMILIA_MONOPARENTAL",
]
